version: '3'

name: yu_smart_city

networks:
  yu_smart_city_network:


x-spark-common: &spark-common
  image: bitnami/spark:3.5
  depends_on:
    - spark-master
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=512M
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    - SPARK_USER=spark
  networks:
    - yu_smart_city_network

services:
  cp-kafka:
      container_name: kafka-kraft
      hostname: kafka-kraft
      ports:
          - 9101:9101
          - 9092:9092
      environment:
          - KAFKA_NODE_ID=1
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092
          - KAFKA_JMX_PORT=9101
          - KAFKA_JMX_HOSTNAME=localhost
          - KAFKA_PROCESS_ROLES=broker,controller
          - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
          - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-kraft:29093
          - KAFKA_LISTENERS=PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092
          - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
          - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
          - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      image: confluentinc/cp-kafka:7.6.1
      # TODO: Add Health Check
      networks:
        - yu_smart_city_network

  spark-master:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 9080:8080
      - 7077:7077
    volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    networks:
        - yu_smart_city_network

  spark-worker-1:
    <<: *spark-common

  spark-worker-2:
    <<: *spark-common
