version: '3'

name: yu_smart_city

networks:
  yu_smart_city_network:
    name: yu_smart_city_network


x-spark-common: &spark-common
  image: bitnami/spark:3.5
  depends_on:
    - spark-master
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    - SPARK_USER=spark
  networks:
    - yu_smart_city_network  
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  my-console:
    image: ubuntu
    container_name: my-console
    restart: on-failure
    command: ["sleep","infinity"]
    ports:
      - 39080:8080
    networks:
      - yu_smart_city_network

  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server --console-address ":9001" /data
    ports:
      - 29000:9000
      - 29001:9001
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - yu_smart_city_network

  cp-kafka:
      container_name: kafka-kraft
      hostname: kafka-kraft
      ports:
          - 9101:9101
          - 9092:9092
      environment:
          - KAFKA_NODE_ID=1
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092
          - KAFKA_JMX_PORT=9101
          - KAFKA_JMX_HOSTNAME=localhost
          - KAFKA_PROCESS_ROLES=broker,controller
          - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
          - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-kraft:29093
          - KAFKA_LISTENERS=PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092
          - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
          - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
          - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      image: confluentinc/cp-kafka:7.6.1
      # TODO: Add Health Check
      networks:
        - yu_smart_city_network
      extra_hosts:
        - "host.docker.internal:host-gateway"

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 9080:8080
      - 9077:7077
      - 9040:4040
    volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    networks:
        - yu_smart_city_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  spark-worker-1:
    container_name: spark-worker-1
    ports:
      - 19081:8081
      - 19040:4040
    <<: *spark-common

  spark-worker-2:
    container_name: spark-worker-2
    ports:
      - 29081:8081
      - 29040:4040
    <<: *spark-common
